# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1)(46e0c16e-b3a4-4d53-a89e-0ad6f8b48943)'
    subscriptionId: '46e0c16e-b3a4-4d53-a89e-0ad6f8b48943'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'kafka-dileep'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

